### ISSUE TITLE
Question about Vue implementation

### ISSUE THREAD

**Issue by jakobrosenberg** [BruceHem/simple-todos#1]
Hi, may I ask why you're not using conventional Vue objects with ``data``, ``methods`` etc.?

Also, what are the benefits of adding @Component to the Vue components?

**Comment by chanlito** [comment]
@jakobrosenberg This is what I like about .vue files & vue itself, you can write in whatever you are most comfortable with.
It all comes down to this:
```html
<script>
// js object
</script>

<script lang="coffee">
// write cs
</script>


<script lang="ts">
// it'd use @Component here, for a bit more typing, IDE intellisense & a little more like backend code-ish 😉
</script>
```

**Comment by jakobrosenberg** [comment]
I'm not sure I fully understand. 🙂

Normally in Vue you'd keep your data in the ``data`` prop, your computed data in the ``computed`` prop, methods in ``methods`` and so forth.
```javascript
{
  data () {
    return {
      firstname: '',
      lastname: ''
    }
  },
  methods: {
    async handleSubmit () {
      await result = somecall()
      return result
    }
  }
}
```

You keep all your data and methods in the root of the Vue object. 
```javascript
{
  firstname: '',
  lastname: '', 
  async handleSubmit () {
    await result = somecall()
    return result
  }
}
```

I wonder if this conflicts with the conventions of Vue or if I'm missing out on a much more efficient way of writing .vue files.

**Comment by chanlito** [comment]
@jakobrosenberg u can write vue components using simple object or class.
